export const RESTAURANT_HEALTH_DASHBOARD_FEATURE_FLAG = "RESTAURANT_HEALTH_DASHBOARD" as const;
export const RESTAURANT_HEALTH_DASHBOARD_ENV_VAR = "NEXT_PUBLIC_ENABLE_RESTAURANT_HEALTH_DASHBOARD" as const;
export const RESTAURANT_HEALTH_DASHBOARD_FEATURE_ID = "PH2D-PRODUCTION-001" as const;
