import type { PluginManifest, PluginPermissions } from "@/plugins/core/sdk";

const permissions = ["admin", "developer"] satisfies PluginPermissions;

export const restaurantHealthDashboardMetadata = {
  id: "PH2D-PRODUCTION-001",
  name: "restaurant-health-dashboard",
  displayName: "Restaurant Health Dashboard",
  description: "SDK-only Admin/Developer diagnostics plugin that validates production plugin readiness.",
  author: "Food Gedi",
  company: "Food Gedi",
  version: "1.0.0",
  license: "Proprietary",
  category: "quality",
  priority: "P2",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions,
  featureFlag: "RESTAURANT_HEALTH_DASHBOARD",
  minimumPluginRuntime: "2.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["admin", "developer"],
  entry: "@/plugins/restaurant-health-dashboard/plugin",
  icon: "restaurant-health-dashboard:icon",
  logo: "restaurant-health-dashboard:logo",
  screenshots: [],
  documentation: "src/plugins/restaurant-health-dashboard/docs/README.md",
  releaseNotes: "FIRST_REAL_PLUGIN.md",
  keywords: ["diagnostics", "health", "sdk", "production"],
  tags: ["phase-2d", "real-plugin", "sdk-only", "diagnostics"],
  bundleSize: 0,
  checksum: "local-production-validation",
  signature: "local-production-validation",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginManifest;
