import type { PluginMetadata } from "@/plugins/core/metadata/types";

export const developerNotesMetadata = {
  id: "PH2B-EXAMPLE-NOTES",
  name: "developer-notes-widget",
  displayName: "Developer Notes Widget",
  description: "Developer-only sample widget that validates SDK storage.",
  author: "Food Gedi",
  company: "Food Gedi",
  version: "1.0.0",
  license: "Proprietary",
  category: "developer",
  priority: "P3",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions: ["developer"],
  featureFlag: "DEVELOPER_NOTES_WIDGET",
  minimumPluginRuntime: "2.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["developer"],
  entry: "@/plugins/examples/developer-notes/plugin",
  screenshots: [],
  documentation: "src/plugins/examples/developer-notes/docs/README.md",
  keywords: ["developer", "notes", "sample"],
  tags: ["phase-2b", "sample"],
  bundleSize: 0,
  checksum: "local-development",
  signature: "local-development",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginMetadata;
