import type { PluginMetadata } from "@/plugins/core/metadata/types";

export const systemInformationMetadata = {
  id: "PH2B-EXAMPLE-SYSTEM",
  name: "system-information-widget",
  displayName: "System Information Widget",
  description: "Developer-only sample widget that validates diagnostics context.",
  author: "Sarva",
  company: "Sarva",
  version: "1.0.0",
  license: "Proprietary",
  category: "developer",
  priority: "P3",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions: ["developer"],
  featureFlag: "SYSTEM_INFORMATION_WIDGET",
  minimumPluginRuntime: "2.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["developer"],
  entry: "@/plugins/examples/system-information/plugin",
  screenshots: [],
  documentation: "src/plugins/examples/system-information/README.md",
  keywords: ["developer", "system", "sample"],
  tags: ["phase-2b", "sample"],
  bundleSize: 0,
  checksum: "local-development",
  signature: "local-development",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginMetadata;
