import type { PluginMetadata } from "@/plugins/core/metadata/types";

export const developerClockMetadata = {
  id: "PH2B-EXAMPLE-CLOCK",
  name: "developer-clock-widget",
  displayName: "Developer Clock Widget",
  description: "Developer-only sample widget that validates SDK UI registration.",
  author: "Sarva",
  company: "Sarva",
  version: "1.0.0",
  license: "Proprietary",
  category: "developer",
  priority: "P3",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions: ["developer"],
  featureFlag: "DEVELOPER_CLOCK_WIDGET",
  minimumPluginRuntime: "2.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["developer"],
  entry: "@/plugins/examples/developer-clock/plugin",
  screenshots: [],
  documentation: "src/plugins/examples/developer-clock/README.md",
  keywords: ["developer", "clock", "sample"],
  tags: ["phase-2b", "sample"],
  bundleSize: 0,
  checksum: "local-development",
  signature: "local-development",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginMetadata;
