"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, BarChart3, CalendarClock, Clipboard, Copy, Download, ExternalLink, Loader2, Megaphone, Play, Plus, QrCode, Save, Search, Send } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SafeImage, IMAGE_FALLBACKS } from "@/components/media/safe-image";
import { marketingToneOptions, whatsappTemplateOptions, type MarketingTone, type WhatsAppTemplateKind } from "@/features/marketing/messageTemplates";
import { buildCampaignMessage, campaignCtas, campaignLayouts, campaignPricing, campaignSlug, campaignTypes, emptyMetrics, socialFormats, smartBadges, type CampaignStatus, type MarketingCampaign } from "@/features/marketing/campaign-engine";
import type { MenuItem, Restaurant } from "@/lib/types";
import { toast } from "@/lib/client-toast";

type Draft = { id?: string; name: string; type: string; status: CampaignStatus; menuItemIds: string[]; template: WhatsAppTemplateKind; tone: MarketingTone; layout: string; socialFormat: string; cta: string; message: string; scheduleAt: string; scheduleKind: string };
const freshDraft = (ids: string[] = []): Draft => ({ name: "Today's Specials", type: "Today's Specials", status: "draft", menuItemIds: ids, template: "todays-special", tone: "professional", layout: "Classic", socialFormat: "WhatsApp", cta: "Order Now", message: "", scheduleAt: "", scheduleKind: "" });

export function CampaignManagerDialog({ open, onOpenChange, menuItems, restaurant, initialItemIds = [] }: { open: boolean; onOpenChange: (open: boolean) => void; menuItems: MenuItem[]; restaurant?: Restaurant; initialItemIds?: string[] }) {
  const [tab, setTab] = useState<"build" | "history" | "analytics">("build");
  const [draft, setDraft] = useState<Draft>(() => freshDraft(initialItemIds));
  const [campaigns, setCampaigns] = useState<MarketingCampaign[]>([]);
  const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [query, setQuery] = useState(""); const [statusFilter, setStatusFilter] = useState("all");
  const restaurantSlug = restaurant?.slug || menuItems[0]?.restaurantSlug || "restaurant"; const restaurantName = restaurant?.displayName || restaurant?.name || restaurantSlug.replace(/-/g, " ");
  const visibleItems = useMemo(() => menuItems.filter((item) => !item.soldOut && item.menuVisibility?.delivery !== false && (item as MenuItem & { status?: string }).status !== "draft"), [menuItems]);
  const selected = useMemo(() => visibleItems.filter((item) => draft.menuItemIds.includes(item.id)), [visibleItems, draft.menuItemIds]);
  const publicPath = draft.menuItemIds.length === 1 && selected[0] ? `/restaurant/${encodeURIComponent(restaurantSlug)}/menu/${encodeURIComponent(campaignSlug(selected[0].name))}` : draft.type === "Category" && selected[0] ? `/restaurant/${encodeURIComponent(restaurantSlug)}/category/${encodeURIComponent(campaignSlug(selected[0].category))}` : `/restaurant/${encodeURIComponent(restaurantSlug)}/campaign/${encodeURIComponent(campaignSlug(draft.name))}`;
  const publicUrl = typeof window === "undefined" ? publicPath : `${window.location.origin}${publicPath}`;
  const message = draft.message || buildCampaignMessage(draft.name, restaurantName, selected, draft.cta, publicUrl);

  useEffect(() => { if (!open) return; void Promise.resolve().then(() => setDraft((current) => current.id ? current : { ...current, menuItemIds: initialItemIds.length ? initialItemIds : current.menuItemIds })); void loadCampaigns(); }, [open]); // eslint-disable-line react-hooks/exhaustive-deps
  async function loadCampaigns() { setLoading(true); try { const response = await fetch(`/api/owner/marketing-campaigns?restaurantId=${encodeURIComponent(restaurantSlug)}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setCampaigns(payload.data ?? []); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load campaigns."); } finally { setLoading(false); } }
  function update(next: Partial<Draft>) { setDraft((current) => ({ ...current, ...next, message: next.message ?? (Object.keys(next).some((key) => ["name", "menuItemIds", "cta"].includes(key)) ? "" : current.message) })); }
  function pickCategory(category: string) { update({ type: "Category", name: `${category} Collection`, menuItemIds: visibleItems.filter((item) => item.category === category).map((item) => item.id) }); }

  async function save(status: CampaignStatus = draft.status) {
    if (!draft.name.trim() || !selected.length) return toast.error("Add a campaign name and at least one available item.");
    setSaving(true); try {
      const body = { ...draft, status, publicSlug: campaignSlug(draft.name), message, restaurantId: restaurantSlug, restaurantSlug, restaurantName, itemSnapshots: selected.map((item) => { const price = campaignPricing(item); return { name: item.name, image: item.image, category: item.category, price: price.original, offerPrice: price.discount ? price.selling : 0, isVeg: item.isVeg, badges: smartBadges(item) }; }) };
      const response = await fetch("/api/owner/marketing-campaigns", { method: draft.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error);
      setDraft((current) => ({ ...current, id: payload.data.id, status })); await loadCampaigns(); toast.success(status === "published" ? "Campaign published." : status === "scheduled" ? "Campaign scheduled." : "Campaign saved.");
    } catch (error) { toast.error(error instanceof Error ? error.message : "Campaign could not be saved."); } finally { setSaving(false); }
  }
  async function track(id: string | undefined, metric: string) { if (!id) return; await fetch("/api/owner/marketing-campaigns", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, restaurantId: restaurantSlug, track: metric }) }).catch(() => undefined); }
  async function copyText(value: string, metric: string) { await navigator.clipboard.writeText(value); void track(draft.id, metric); toast.success("Copied."); }
  function editCampaign(campaign: MarketingCampaign, duplicate = false) { setDraft({ id: duplicate ? undefined : campaign.id, name: duplicate ? `${campaign.name} Copy` : campaign.name, type: campaign.type, status: "draft", menuItemIds: campaign.menuItemIds, template: campaign.template, tone: campaign.tone, layout: campaign.layout, socialFormat: campaign.socialFormat, cta: campaign.cta, message: campaign.message, scheduleAt: campaign.scheduleAt ?? "", scheduleKind: campaign.scheduleKind ?? "" }); setTab("build"); }
  async function archive(campaign: MarketingCampaign) { setDraft((current) => ({ ...current, id: campaign.id })); const response = await fetch("/api/owner/marketing-campaigns", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...campaign, restaurantId: restaurantSlug, status: "archived" }) }); if (response.ok) await loadCampaigns(); }
  async function share() { if (!draft.id) await save("published"); window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, "_blank", "noopener,noreferrer"); void track(draft.id, "whatsappShares"); }
  async function download(kind: "poster" | "qr") { if (kind === "qr") await downloadQr(publicUrl, `${campaignSlug(draft.name)}-qr.png`); else await downloadCampaignPoster(draft, selected, restaurantName, publicUrl); void track(draft.id, kind === "qr" ? "qrDownloads" : "posterDownloads"); }

  const filtered = campaigns.filter((campaign) => (statusFilter === "all" || campaign.status === statusFilter) && `${campaign.name} ${campaign.type}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  const totals = campaigns.reduce((out, campaign) => { out.campaigns += 1; for (const key of Object.keys(out.metrics) as Array<keyof MarketingCampaign["metrics"]>) out.metrics[key] += campaign.metrics?.[key] ?? 0; return out; }, { campaigns: 0, metrics: emptyMetrics() });
  const reach = totals.metrics.whatsappShares * 25 + totals.metrics.copiedMessages * 10 + totals.metrics.qrDownloads * 5; const conversion = totals.metrics.clicks ? (totals.metrics.orders / totals.metrics.clicks) * 100 : 0;

  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[96dvh] max-w-7xl overflow-hidden p-0 max-sm:bottom-0 max-sm:left-0 max-sm:top-auto max-sm:w-full max-sm:max-w-none max-sm:translate-x-0 max-sm:translate-y-0 max-sm:rounded-b-none"><DialogHeader className="border-b px-5 py-4 pr-12"><DialogTitle>Campaign Manager</DialogTitle><DialogDescription>Create, schedule, reuse and measure multi-item marketing campaigns.</DialogDescription></DialogHeader>
    <nav className="flex gap-2 overflow-x-auto border-b px-4 py-2" aria-label="Campaign manager sections">{(["build", "history", "analytics"] as const).map((value) => <Button key={value} variant={tab === value ? "default" : "ghost"} onClick={() => setTab(value)} className="capitalize">{value === "build" ? <Megaphone className="size-4" /> : value === "history" ? <CalendarClock className="size-4" /> : <BarChart3 className="size-4" />}{value}</Button>)}</nav>
    <div className="max-h-[calc(96dvh-142px)] overflow-y-auto p-4 lg:p-5">{tab === "build" ? <div className="grid gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]"><section className="space-y-4">
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Campaign name"><Input value={draft.name} onChange={(event) => update({ name: event.target.value })} /></Field><Select label="Campaign type" value={draft.type} values={campaignTypes} onChange={(type) => update({ type })} /><Select label="Message template" value={draft.template} values={whatsappTemplateOptions.map((item) => item.value)} labels={Object.fromEntries(whatsappTemplateOptions.map((item) => [item.value, item.label]))} onChange={(template) => update({ template: template as WhatsAppTemplateKind })} /><Select label="Marketing tone" value={draft.tone} values={marketingToneOptions.map((item) => item.value)} labels={Object.fromEntries(marketingToneOptions.map((item) => [item.value, item.label]))} onChange={(tone) => update({ tone: tone as MarketingTone })} /><Select label="Poster template" value={draft.layout} values={campaignLayouts} onChange={(layout) => update({ layout })} /><Select label="Social export" value={draft.socialFormat} values={socialFormats} onChange={(socialFormat) => update({ socialFormat })} /><Select label="CTA" value={draft.cta} values={campaignCtas} onChange={(cta) => update({ cta })} /><Select label="Schedule preset" value={draft.scheduleKind} values={["", "Lunch", "Dinner", "Weekend", "Festival", "Birthday"]} labels={{ "": "No schedule" }} onChange={(scheduleKind) => update({ scheduleKind, status: scheduleKind ? "scheduled" : "draft" })} /></div>
      {draft.scheduleKind ? <Field label="Schedule date and time"><Input type="datetime-local" value={draft.scheduleAt} onChange={(event) => update({ scheduleAt: event.target.value })} /></Field> : null}
      <div><p className="mb-2 text-xs font-black uppercase text-muted-foreground">Category marketing</p><div className="flex gap-2 overflow-x-auto pb-1">{[...new Set(visibleItems.map((item) => item.category).filter(Boolean))].map((category) => <Button key={category} variant="outline" className="shrink-0" onClick={() => pickCategory(category)}>{category}</Button>)}</div></div>
      <fieldset><legend className="mb-2 text-xs font-black uppercase text-muted-foreground">Menu items ({selected.length} selected)</legend><div className="grid max-h-64 gap-2 overflow-y-auto rounded-xl border p-2 sm:grid-cols-2">{visibleItems.map((item) => <label key={item.id} className="flex min-h-14 cursor-pointer items-center gap-3 rounded-lg p-2 hover:bg-muted focus-within:ring-2 focus-within:ring-ring"><input type="checkbox" checked={draft.menuItemIds.includes(item.id)} onChange={(event) => update({ menuItemIds: event.target.checked ? [...draft.menuItemIds, item.id] : draft.menuItemIds.filter((id) => id !== item.id) })} /><span className="relative size-10 shrink-0 overflow-hidden rounded-md"><SafeImage src={item.image} alt="" fill fallbackSrc={IMAGE_FALLBACKS.food} sizes="40px" className="object-cover" /></span><span className="min-w-0"><span className="block truncate text-sm font-black">{item.name}</span><span className="text-xs text-muted-foreground">{item.category} · ₹{item.deliveryPrice ?? item.price}</span></span></label>)}</div></fieldset>
      <Field label="Campaign message"><textarea className="min-h-48 w-full rounded-xl border bg-background p-3 text-sm leading-6" value={message} onChange={(event) => update({ message: event.target.value })} /></Field>
      <div className="sticky bottom-0 grid grid-cols-2 gap-2 rounded-xl border bg-background/95 p-3 shadow-lg backdrop-blur sm:flex sm:flex-wrap"><Button variant="outline" onClick={() => setDraft(freshDraft())}><Plus className="size-4" />New</Button><Button variant="outline" onClick={() => void save("draft")} disabled={saving}><Save className="size-4" />Save Draft</Button><Button onClick={() => void save(draft.scheduleKind ? "scheduled" : "published")} disabled={saving}>{saving ? <Loader2 className="size-4 animate-spin" /> : <Play className="size-4" />}{draft.scheduleKind ? "Schedule" : "Publish"}</Button><Button className="bg-emerald-600 hover:bg-emerald-700" onClick={() => void share()}><Send className="size-4" />Share</Button></div>
    </section><aside className="space-y-3"><CampaignPreview draft={draft} items={selected} restaurantName={restaurantName} /><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => void copyText(message, "copiedMessages")}><Clipboard className="size-4" />Message</Button><Button variant="outline" onClick={() => void copyText(publicUrl, "copiedLinks")}><ExternalLink className="size-4" />Link</Button><Button variant="outline" onClick={() => void download("poster")}><Download className="size-4" />Poster</Button><Button variant="outline" onClick={() => void download("qr")}><QrCode className="size-4" />QR</Button></div><p className="break-all text-xs font-semibold text-muted-foreground">{publicUrl}</p></aside></div> : tab === "history" ? <section className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search campaign history" /></label><Select label="" value={statusFilter} values={["all", "draft", "published", "scheduled", "archived"]} onChange={setStatusFilter} /><Button variant="outline" onClick={() => exportCampaigns(campaigns)}><Download className="size-4" />Export</Button></div>{loading ? <p className="py-12 text-center"><Loader2 className="mx-auto size-5 animate-spin" /></p> : filtered.length ? <div className="grid gap-3">{filtered.map((campaign) => <article key={campaign.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><strong>{campaign.name}</strong><span className="rounded-full bg-muted px-2 py-0.5 text-xs font-black capitalize">{campaign.status}</span></div><p className="mt-1 text-xs text-muted-foreground">{campaign.type} · {campaign.menuItemIds.length} items · Modified {new Date(campaign.updatedAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => editCampaign(campaign)}><Play className="size-4" />Re-run</Button><Button size="sm" variant="outline" onClick={() => editCampaign(campaign, true)}><Copy className="size-4" />Duplicate</Button>{campaign.status !== "archived" ? <Button size="sm" variant="outline" onClick={() => void archive(campaign)}><Archive className="size-4" />Archive</Button> : null}</div></article>)}</div> : <p className="rounded-xl border p-10 text-center text-muted-foreground">No campaigns match this search.</p>}</section> : <Analytics campaigns={campaigns} totals={totals} reach={reach} conversion={conversion} />}</div>
  </DialogContent></Dialog>;
}

function CampaignPreview({ draft, items, restaurantName }: { draft: Draft; items: MenuItem[]; restaurantName: string }) { return <section className={`overflow-hidden rounded-2xl border bg-card shadow-sm ${draft.layout === "Luxury" ? "bg-slate-950 text-white" : draft.layout === "Festival" ? "bg-amber-50" : ""}`} aria-label="Live promotional poster preview"><div className="p-4"><p className="text-xs font-black uppercase tracking-widest text-primary">{draft.layout} · {draft.socialFormat}</p><h3 className="mt-1 text-2xl font-black">{draft.name}</h3><p className="text-sm opacity-70">{restaurantName}</p></div><div className="grid grid-cols-2 gap-1 px-4">{items.slice(0, 4).map((item) => <div key={item.id} className="relative aspect-square overflow-hidden rounded-lg"><SafeImage src={item.image} alt={item.name} fill fallbackSrc={IMAGE_FALLBACKS.food} sizes="180px" className="object-cover" /><span className="absolute inset-x-0 bottom-0 bg-black/70 p-2 text-xs font-black text-white">{item.name}<br />₹{item.deliveryPrice ?? item.price}</span></div>)}</div><div className="m-4 rounded-xl bg-primary p-3 text-center font-black text-primary-foreground">{draft.cta}</div></section>; }
function Analytics({ campaigns, totals, reach, conversion }: { campaigns: MarketingCampaign[]; totals: { campaigns: number; metrics: MarketingCampaign["metrics"] }; reach: number; conversion: number }) { const top = [...campaigns].sort((a, b) => (b.metrics?.whatsappShares ?? 0) - (a.metrics?.whatsappShares ?? 0))[0]; const cards = [["Campaigns Created", totals.campaigns], ["WhatsApp Shares", totals.metrics.whatsappShares], ["Poster Downloads", totals.metrics.posterDownloads], ["Copied Links", totals.metrics.copiedLinks], ["Copied Messages", totals.metrics.copiedMessages], ["QR Downloads", totals.metrics.qrDownloads], ["Estimated Reach", reach], ["Orders Generated", totals.metrics.orders], ["Revenue Generated", `₹${totals.metrics.revenue}`], ["Conversion Rate", `${conversion.toFixed(1)}%`], ["Most Shared Item", top?.itemSnapshots?.[0]?.name || "—"], ["Top Campaign", top?.name || "—"]]; return <section><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-card p-4"><p className="text-xs font-black uppercase text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>)}</div></section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-black text-muted-foreground">{label}<span className="mt-1 block text-foreground">{children}</span></label>; }
function Select({ label, value, values, labels = {}, onChange }: { label: string; value: string; values: readonly string[]; labels?: Record<string, string>; onChange: (value: string) => void }) { return <Field label={label}><select className="h-11 w-full rounded-lg border bg-background px-3 text-sm font-bold" value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item} value={item}>{labels[item] || item}</option>)}</select></Field>; }
function exportCampaigns(campaigns: MarketingCampaign[]) { const rows = [["Name", "Type", "Status", "Created", "Modified", "Items", "Template", "Tone", "CTA", "Shares", "Downloads"], ...campaigns.map((item) => [item.name, item.type, item.status, item.createdAt, item.updatedAt, item.menuItemIds.length, item.template, item.tone, item.cta, item.metrics?.whatsappShares ?? 0, item.metrics?.posterDownloads ?? 0])]; const blob = new Blob([rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n")], { type: "text/csv" }); saveBlob(blob, "marketing-campaign-history.csv"); }
async function downloadQr(url: string, name: string) { const qr = await import("qrcode"); const data = await qr.toDataURL(url, { width: 1000, margin: 2 }); const link = document.createElement("a"); link.download = name; link.href = data; link.click(); }
async function downloadCampaignPoster(draft: Draft, items: MenuItem[], restaurantName: string, url: string) { const size = posterSize(draft.socialFormat); const canvas = document.createElement("canvas"); canvas.width = size[0]; canvas.height = size[1]; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.fillStyle = draft.layout === "Luxury" ? "#0f172a" : draft.layout === "Festival" ? "#fef3c7" : "#ffffff"; ctx.fillRect(0, 0, ...size); const dark = draft.layout === "Luxury"; ctx.fillStyle = dark ? "#fff" : "#111827"; ctx.font = `900 ${Math.round(size[0] * .06)}px system-ui`; ctx.fillText(draft.name.slice(0, 28), 60, 100); ctx.font = `600 ${Math.round(size[0] * .025)}px system-ui`; ctx.fillText(restaurantName.slice(0, 42), 60, 145); const cols = items.length === 1 ? 1 : 2; const gap = 20; const w = (size[0] - 120 - gap * (cols - 1)) / cols; const h = Math.min(w * .8, (size[1] - 360) / Math.ceil(Math.min(items.length, 4) / cols)); for (const [index, item] of items.slice(0, 4).entries()) { const x = 60 + (index % cols) * (w + gap); const y = 190 + Math.floor(index / cols) * (h + 80); const image = await loadImage(item.image).catch(() => null); if (image) ctx.drawImage(image, x, y, w, h); ctx.fillStyle = dark ? "#fff" : "#111827"; ctx.font = `800 ${Math.round(size[0] * .025)}px system-ui`; ctx.fillText(item.name.slice(0, 24), x, y + h + 32); ctx.font = `700 ${Math.round(size[0] * .022)}px system-ui`; ctx.fillText(`₹${item.deliveryPrice ?? item.price}`, x, y + h + 62); } const qr = await import("qrcode"); const qrImage = await loadImage(await qr.toDataURL(url, { width: 180, margin: 1 })); ctx.drawImage(qrImage, size[0] - 230, size[1] - 230, 170, 170); ctx.fillStyle = dark ? "#fff" : "#166534"; ctx.font = `900 ${Math.round(size[0] * .035)}px system-ui`; ctx.fillText(draft.cta, 60, size[1] - 120); canvas.toBlob((blob) => blob && saveBlob(blob, `${campaignSlug(draft.name)}-${campaignSlug(draft.socialFormat)}.png`), "image/png"); }
function posterSize(format: string): [number, number] { if (["Instagram Story", "WhatsApp Status"].includes(format)) return [1080, 1920]; if (format === "Instagram Feed") return [1080, 1080]; if (["Facebook", "X"].includes(format)) return [1200, 630]; return [1080, 1350]; }
function loadImage(src: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.crossOrigin = "anonymous"; image.onload = () => resolve(image); image.onerror = reject; image.src = src; }); }
function saveBlob(blob: Blob, name: string) { const link = document.createElement("a"); link.download = name; link.href = URL.createObjectURL(blob); link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
