export const QUALITY_DIAGNOSTICS_FEATURE_ID = "PH1-QD-001";
export const QUALITY_DIAGNOSTICS_FLAG = "QUALITY_DIAGNOSTICS";
export const QUALITY_DIAGNOSTICS_ENV_VAR = "NEXT_PUBLIC_ENABLE_QUALITY_DIAGNOSTICS";
