import type { PluginMetadata } from "@/plugins/core/metadata/types";

export const qualityDiagnosticsMetadata = {
  id: "PH1-QD-001",
  name: "quality-diagnostics",
  displayName: "Quality Diagnostics",
  description: "Optional render, long-task, and memory diagnostics for controlled profiling.",
  author: "Food Gedi",
  company: "Food Gedi",
  website: "",
  email: "",
  version: "1.0.0",
  license: "Proprietary",
  category: "quality",
  priority: "P1",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions: ["developer"],
  featureFlag: "QUALITY_DIAGNOSTICS",
  minimumAppVersion: "v1.0.0-rc4",
  minimumPluginRuntime: "1.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["developer"],
  entry: "@/plugins/quality-diagnostics/routes/runtime",
  icon: "",
  logo: "",
  screenshots: [],
  documentation: "src/plugins/quality-diagnostics/docs/README.md",
  homepage: "",
  repository: "",
  issues: "",
  releaseNotes: "Initial disabled diagnostics plugin.",
  keywords: ["quality", "diagnostics", "performance", "memory"],
  tags: ["phase-1", "disabled-default"],
  bundleSize: 0,
  checksum: "local-development",
  signature: "local-development",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginMetadata;
