import type { PluginMetadata } from "@/plugins/core/metadata/types";

export const themePreviewMetadata = {
  id: "PH2B-EXAMPLE-THEME",
  name: "theme-preview-widget",
  displayName: "Theme Preview Widget",
  description: "Developer-only sample widget that validates theme and asset APIs.",
  author: "Sarva",
  company: "Sarva",
  version: "1.0.0",
  license: "Proprietary",
  category: "developer",
  priority: "P3",
  dependencies: [],
  peerDependencies: [],
  optionalDependencies: [],
  softDependencies: [],
  developmentDependencies: [],
  permissions: ["developer"],
  featureFlag: "THEME_PREVIEW_WIDGET",
  minimumPluginRuntime: "2.0.0",
  compatiblePlatforms: ["web"],
  supportedModules: ["developer"],
  entry: "@/plugins/examples/theme-preview/plugin",
  screenshots: [],
  documentation: "src/plugins/examples/theme-preview/docs/README.md",
  keywords: ["developer", "theme", "sample"],
  tags: ["phase-2b", "sample"],
  bundleSize: 0,
  checksum: "local-development",
  signature: "local-development",
  installSize: 0,
  health: "unknown",
  status: "available",
} satisfies PluginMetadata;
